= Hyperskill exercises https://hi.hyperskill.org/about

== case2221
Integer types and operations arrow right Snail
https://hyperskill.org/learn/step/2221

== case2484
Java → Multiset
https://hyperskill.org/learn/step/2484

== case2784
Queue and Stack → Getting the max element of a stack
https://hyperskill.org/learn/step/2784

== case3126
Recursion → Number of decompositions
https://hyperskill.org/learn/step/3126

== case3130
Binary search in Java → Find array elements in another array
https://hyperskill.org/learn/step/3130

== case3131
Binary search in Java → Find a fixed point in an array
https://hyperskill.org/learn/step/3131

== case3655
Java → Sherlock Holmes - 2
https://hyperskill.org/learn/step/3655

== case3658
Java → Html Parser
https://hyperskill.org/learn/step/3658

== case3791
Processing strings  -> Create a euphonious word
https://hyperskill.org/learn/step/3791

== case3825
Jump search in Java → Print comparisons
https://hyperskill.org/learn/step/3825

== case4838
Reading files -> World population
https://hyperskill.org/learn/step/4838

== case4839
Reading files -> Count even numbers
https://hyperskill.org/learn/step/4839

== case4840
Reading files -> The sum of numbers in a file
https://hyperskill.org/learn/step/4840

== case4841
Reading files -> Count numbers in a file
https://hyperskill.org/learn/step/4841

== case4842
Reading files -> Find the greatest number in a file
https://hyperskill.org/learn/step/4842

== case5718
Searching a substring in Java  -> Non-overlapping occurrences
https://hyperskill.org/learn/step/5718

== case5722
Rabin-Karp algorithm in Java → A substring of the maximal length
https://hyperskill.org/learn/step/5722

== case5723
Rabin-Karp algorithm in Java → The number of equal substring pairs
https://hyperskill.org/learn/step/5723

== case5729
Knuth-Morris-Pratt algorithm in Java → Non-overlapping occurrences of a pattern
https://hyperskill.org/learn/step/5729

== case5730
Knuth-Morris-Pratt algorithm in Java → Number of distinct substrings in a string
https://hyperskill.org/learn/step/5730

== case5731
Knuth-Morris-Pratt algorithm in Java → Finding substrings in a matrix
https://hyperskill.org/learn/step/5731

== case6951
Hash table in Java → Phone Book
https://hyperskill.org/learn/step/6951

== case7259
Fixed-size array → Calculations
https://hyperskill.org/learn/step/7259
